# Generated by Django 6.1.1 on 2026-10-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseoffer',
            name='offer_type',
            field=models.CharField(choices=[('PRODUCT', 'Product Offer'), ('CATEGORY', 'Category Offer'), ('REFERRAL', 'Referral Offer')], max_length=20),
        ),
    ]
