# Generated by Django 6.1.1 on 2026-10-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_admin', '0002_alter_baseoffer_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseoffer',
            name='offer_type',
            field=models.CharField(choices=[('PRODUCT', 'Product Offer'), ('CATEGORY', 'Category Offer')], max_length=20),
        ),
    ]
