# Generated by Django 6.1.1 on 2026-09-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('other', 'Other')], default='home', max_length=10),
        ),
    ]
